/**
 * Seed data for current standard meta archetypes (March 2026).
 * Based on Limitless TCG tournament data.
 * identifier_cards are card names used for rule-based deck classification.
 *
 * IDs MUST match those used in seed-official-tournaments.ts (source of truth).
 */
export const STANDARD_ARCHETYPES = [
  // S tier
  {
    id: "dragapult-charizard",
    name: "Dragapult Charizard",
    slug: "dragapult-charizard",
    identifierCards: ["Dragapult ex", "Charizard ex", "Dreepy"],
    tier: "S" as const,
    format: "standard" as const,
  },
  {
    id: "raging-bolt-ogerpon",
    name: "Raging Bolt Ogerpon",
    slug: "raging-bolt-ogerpon",
    identifierCards: ["Raging Bolt ex", "Ogerpon ex"],
    tier: "S" as const,
    format: "standard" as const,
  },
  // A tier
  {
    id: "gardevoir-ex-sv",
    name: "Gardevoir",
    slug: "gardevoir-ex-sv",
    identifierCards: ["Gardevoir ex", "Kirlia", "Ralts"],
    tier: "A" as const,
    format: "standard" as const,
  },
  {
    id: "gardevoir-jellicent",
    name: "Gardevoir Jellicent",
    slug: "gardevoir-jellicent",
    identifierCards: ["Gardevoir ex", "Jellicent"],
    tier: "A" as const,
    format: "standard" as const,
  },
  {
    id: "dragapult-dusknoir",
    name: "Dragapult Dusknoir",
    slug: "dragapult-dusknoir",
    identifierCards: ["Dragapult ex", "Dusknoir"],
    tier: "A" as const,
    format: "standard" as const,
  },
  {
    id: "dragapult-blaziken",
    name: "Dragapult Blaziken",
    slug: "dragapult-blaziken",
    identifierCards: ["Dragapult ex", "Blaziken"],
    tier: "A" as const,
    format: "standard" as const,
  },
  {
    id: "conkeldurr",
    name: "Conkeldurr",
    slug: "conkeldurr",
    identifierCards: ["Conkeldurr"],
    tier: "A" as const,
    format: "standard" as const,
  },
  {
    id: "n-zoroark",
    name: "N's Zoroark",
    slug: "n-zoroark",
    identifierCards: ["N's Zoroark"],
    tier: "A" as const,
    format: "standard" as const,
  },
  {
    id: "mega-absol-box",
    name: "Mega Absol Box",
    slug: "mega-absol-box",
    identifierCards: ["Mega Absol"],
    tier: "A" as const,
    format: "standard" as const,
  },
  {
    id: "charizard-noctowl",
    name: "Charizard Noctowl",
    slug: "charizard-noctowl",
    identifierCards: ["Charizard ex", "Noctowl"],
    tier: "A" as const,
    format: "standard" as const,
  },
  // B tier
  {
    id: "grimmsnarl-froslass",
    name: "Grimmsnarl Froslass",
    slug: "grimmsnarl-froslass",
    identifierCards: ["Grimmsnarl", "Froslass"],
    tier: "B" as const,
    format: "standard" as const,
  },
  {
    id: "ogerpon-meganium",
    name: "Ogerpon Meganium",
    slug: "ogerpon-meganium",
    identifierCards: ["Ogerpon ex", "Meganium"],
    tier: "B" as const,
    format: "standard" as const,
  },
  {
    id: "charizard-pidgeot",
    name: "Charizard Pidgeot",
    slug: "charizard-pidgeot",
    identifierCards: ["Charizard ex", "Pidgeot ex"],
    tier: "B" as const,
    format: "standard" as const,
  },
  {
    id: "alakazam-dudunsparce",
    name: "Alakazam Dudunsparce",
    slug: "alakazam-dudunsparce",
    identifierCards: ["Alakazam ex", "Dudunsparce"],
    tier: "B" as const,
    format: "standard" as const,
  },
  {
    id: "cynthias-garchomp",
    name: "Cynthia's Garchomp",
    slug: "cynthias-garchomp",
    identifierCards: ["Cynthia's Garchomp ex"],
    tier: "B" as const,
    format: "standard" as const,
  },
  {
    id: "greninja-blaziken",
    name: "Greninja Blaziken",
    slug: "greninja-blaziken",
    identifierCards: ["Greninja ex", "Blaziken"],
    tier: "B" as const,
    format: "standard" as const,
  },
  {
    id: "greninja-ex",
    name: "Greninja",
    slug: "greninja-ex",
    identifierCards: ["Greninja ex"],
    tier: "B" as const,
    format: "standard" as const,
  },
  {
    id: "gholdengo-lunatone",
    name: "Gholdengo Lunatone",
    slug: "gholdengo-lunatone",
    identifierCards: ["Gholdengo ex", "Lunatone"],
    tier: "B" as const,
    format: "standard" as const,
  },
  // C tier
  {
    id: "crustle-dri",
    name: "Crustle",
    slug: "crustle-dri",
    identifierCards: ["Crustle"],
    tier: "C" as const,
    format: "standard" as const,
  },
  {
    id: "lucario-hariyama",
    name: "Lucario Hariyama",
    slug: "lucario-hariyama",
    identifierCards: ["Lucario", "Hariyama"],
    tier: "C" as const,
    format: "standard" as const,
  },
  {
    id: "ethans-typhlosion",
    name: "Ethan's Typhlosion",
    slug: "ethans-typhlosion",
    identifierCards: ["Ethan's Typhlosion ex"],
    tier: "C" as const,
    format: "standard" as const,
  },
  {
    id: "ho-oh-armarouge",
    name: "Ho-Oh Armarouge",
    slug: "ho-oh-armarouge",
    identifierCards: ["Ho-Oh ex", "Armarouge"],
    tier: "C" as const,
    format: "standard" as const,
  },
  {
    id: "hydreigon",
    name: "Hydreigon",
    slug: "hydreigon",
    identifierCards: ["Hydreigon ex"],
    tier: "C" as const,
    format: "standard" as const,
  },
  {
    id: "hops-zacian",
    name: "Hop's Zacian",
    slug: "hops-zacian",
    identifierCards: ["Hop's Zacian V"],
    tier: "C" as const,
    format: "standard" as const,
  },
  {
    id: "froslass-munkidori",
    name: "Froslass Munkidori",
    slug: "froslass-munkidori",
    identifierCards: ["Froslass", "Munkidori"],
    tier: "C" as const,
    format: "standard" as const,
  },
  {
    id: "pidgeot-control",
    name: "Pidgeot Control",
    slug: "pidgeot-control",
    identifierCards: ["Pidgeot ex"],
    tier: "C" as const,
    format: "standard" as const,
  },
  // D tier
  {
    id: "marnies-grimmsnarl",
    name: "Marnie's Grimmsnarl",
    slug: "marnies-grimmsnarl",
    identifierCards: ["Marnie's Grimmsnarl ex"],
    tier: "D" as const,
    format: "standard" as const,
  },
  {
    id: "mega-lucario",
    name: "Mega Lucario",
    slug: "mega-lucario",
    identifierCards: ["Mega Lucario ex"],
    tier: "D" as const,
    format: "standard" as const,
  },
  {
    id: "tera-box",
    name: "Tera Box",
    slug: "tera-box",
    identifierCards: ["Terapagos ex"],
    tier: "D" as const,
    format: "standard" as const,
  },
  {
    id: "kangaskhan-bouffalant",
    name: "Kangaskhan Bouffalant",
    slug: "kangaskhan-bouffalant",
    identifierCards: ["Kangaskhan", "Bouffalant"],
    tier: "D" as const,
    format: "standard" as const,
  },
  {
    id: "lopunny-dusknoir",
    name: "Lopunny Dusknoir",
    slug: "lopunny-dusknoir",
    identifierCards: ["Lopunny", "Dusknoir"],
    tier: "D" as const,
    format: "standard" as const,
  },
];
