/**
 * Seed data for current standard meta archetypes (March 2026).
 * Based on Limitless TCG tournament data.
 * identifier_cards are card names used for rule-based deck classification.
 */
export const STANDARD_ARCHETYPES = [
  {
    id: "dragapult-charizard",
    name: "Dragapult Charizard",
    slug: "dragapult-charizard",
    identifierCards: ["Dragapult ex", "Charizard ex", "Dreepy"],
    tier: "S" as const,
    format: "standard" as const,
  },
  {
    id: "raging-bolt-ogerpon",
    name: "Raging Bolt Ogerpon",
    slug: "raging-bolt-ogerpon",
    identifierCards: ["Raging Bolt ex", "Ogerpon ex"],
    tier: "S" as const,
    format: "standard" as const,
  },
  {
    id: "gardevoir",
    name: "Gardevoir",
    slug: "gardevoir",
    identifierCards: ["Gardevoir ex", "Kirlia", "Ralts"],
    tier: "A" as const,
    format: "standard" as const,
  },
  {
    id: "gardevoir-jellicent",
    name: "Gardevoir Jellicent",
    slug: "gardevoir-jellicent",
    identifierCards: ["Gardevoir ex", "Jellicent"],
    tier: "A" as const,
    format: "standard" as const,
  },
  {
    id: "dragapult",
    name: "Dragapult",
    slug: "dragapult",
    identifierCards: ["Dragapult ex", "Dreepy", "Drakloak"],
    tier: "A" as const,
    format: "standard" as const,
  },
  {
    id: "dragapult-dusknoir",
    name: "Dragapult Dusknoir",
    slug: "dragapult-dusknoir",
    identifierCards: ["Dragapult ex", "Dusknoir"],
    tier: "A" as const,
    format: "standard" as const,
  },
  {
    id: "conkeldurr",
    name: "Conkeldurr",
    slug: "conkeldurr",
    identifierCards: ["Conkeldurr"],
    tier: "A" as const,
    format: "standard" as const,
  },
  {
    id: "ns-zoroark",
    name: "N's Zoroark",
    slug: "ns-zoroark",
    identifierCards: ["N's Zoroark"],
    tier: "A" as const,
    format: "standard" as const,
  },
  {
    id: "mega-absol-box",
    name: "Mega Absol Box",
    slug: "mega-absol-box",
    identifierCards: ["Mega Absol"],
    tier: "A" as const,
    format: "standard" as const,
  },
  {
    id: "grimmsnarl-froslass",
    name: "Grimmsnarl Froslass",
    slug: "grimmsnarl-froslass",
    identifierCards: ["Grimmsnarl", "Froslass"],
    tier: "B" as const,
    format: "standard" as const,
  },
  {
    id: "ogerpon-meganium",
    name: "Ogerpon Meganium",
    slug: "ogerpon-meganium",
    identifierCards: ["Ogerpon ex", "Meganium"],
    tier: "B" as const,
    format: "standard" as const,
  },
  {
    id: "charizard-pidgeot",
    name: "Charizard Pidgeot",
    slug: "charizard-pidgeot",
    identifierCards: ["Charizard ex", "Pidgeot ex"],
    tier: "B" as const,
    format: "standard" as const,
  },
  {
    id: "alakazam",
    name: "Alakazam",
    slug: "alakazam",
    identifierCards: ["Alakazam"],
    tier: "B" as const,
    format: "standard" as const,
  },
  {
    id: "cynthias-garchomp",
    name: "Cynthia's Garchomp",
    slug: "cynthias-garchomp",
    identifierCards: ["Cynthia's Garchomp"],
    tier: "B" as const,
    format: "standard" as const,
  },
  {
    id: "greninja-blaziken",
    name: "Greninja Blaziken",
    slug: "greninja-blaziken",
    identifierCards: ["Greninja", "Blaziken"],
    tier: "B" as const,
    format: "standard" as const,
  },
  {
    id: "greninja",
    name: "Greninja",
    slug: "greninja",
    identifierCards: ["Greninja"],
    tier: "B" as const,
    format: "standard" as const,
  },
  {
    id: "crustle",
    name: "Crustle",
    slug: "crustle",
    identifierCards: ["Crustle"],
    tier: "C" as const,
    format: "standard" as const,
  },
  {
    id: "lucario-hariyama",
    name: "Lucario Hariyama",
    slug: "lucario-hariyama",
    identifierCards: ["Lucario", "Hariyama"],
    tier: "C" as const,
    format: "standard" as const,
  },
  {
    id: "ethans-typhlosion",
    name: "Ethan's Typhlosion",
    slug: "ethans-typhlosion",
    identifierCards: ["Ethan's Typhlosion"],
    tier: "C" as const,
    format: "standard" as const,
  },
  {
    id: "ho-oh-armarouge",
    name: "Ho-Oh Armarouge",
    slug: "ho-oh-armarouge",
    identifierCards: ["Ho-Oh", "Armarouge"],
    tier: "C" as const,
    format: "standard" as const,
  },
  {
    id: "hydreigon",
    name: "Hydreigon",
    slug: "hydreigon",
    identifierCards: ["Hydreigon"],
    tier: "C" as const,
    format: "standard" as const,
  },
  {
    id: "gholdengo-lunatone",
    name: "Gholdengo Lunatone",
    slug: "gholdengo-lunatone",
    identifierCards: ["Gholdengo ex", "Lunatone"],
    tier: "C" as const,
    format: "standard" as const,
  },
  {
    id: "hops-zacian",
    name: "Hop's Zacian",
    slug: "hops-zacian",
    identifierCards: ["Hop's Zacian"],
    tier: "C" as const,
    format: "standard" as const,
  },
  {
    id: "marnies-grimmsnarl",
    name: "Marnie's Grimmsnarl",
    slug: "marnies-grimmsnarl",
    identifierCards: ["Marnie's Grimmsnarl"],
    tier: "D" as const,
    format: "standard" as const,
  },
  {
    id: "mega-lucario",
    name: "Mega Lucario",
    slug: "mega-lucario",
    identifierCards: ["Mega Lucario"],
    tier: "D" as const,
    format: "standard" as const,
  },
];
